# Generated by Django 4.1.7 on 2024-10-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
