# Generated by Django 4.1.7 on 2024-10-18 13:04

from django.db import migrations, models
import tools.models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0002_apikey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.CharField(
                default=tools.models.generate_key, max_length=50, unique=True
            ),
        ),
    ]
